#+TITLE:     MySQL ZIP Archive版本安装说明
#+AUTHOR:    王晓东（Xiaodong Wang）
#+EMAIL:     wangxiaodong@ouc.edu.cn

#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  zh
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../orgcss/worg.css" />
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   ^:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont{SimSun}

* 系统环境

- 硬件 :: Surface Pro 4；
- 操作系统 :: Windows 10专业版 16299.19 64bit；
- MySQL :: MySQL Community Server 5.7.20，Windows (x86,64bit) ZIP Archive；
- MySQL安装路径 :: C:\MySQL，请视自己计算机情况选择安装目录。


* 软件下载

- MySQL下载地址：https://dev.mysql.com/downloads/mysql/
- 下载版本：Windows (x86, 64-bit), ZIP Archive，mysql-5.7.20-winx64.zip

* 软件安装

使用管理员权限打开命令提示符，步骤：开始菜单选择Windows系统 - 命令提示符 - 在其上点击右键选择 - 更多 - 以管理员身份运行。

定位到C盘根目录，创建MySQL目录。

#+BEGIN_SRC dos
C:\>md MySQL
#+END_SRC

将所下载的MySQL软件压缩包mysql-5.7.20-winx64.zip放在MySQL目录下，并使用解压缩工具（WinRAR等）解压缩；cd到解压目录内，新建my.ini文件，并将以下内容拷贝到my.ini文件内。

#+BEGIN_SRC 
[mysql]
# 设置mysql客户端默认字符集
default-character-set=utf8 
[mysqld]
#设置3306端口
port = 3306 
# 设置mysql的安装目录
basedir=C:\MySQL\mysql-5.7.20-winx64
# 设置mysql数据库的数据的存放目录
datadir=C:\MySQL\mysql-5.7.20-winx64\data
# 允许最大连接数
max_connections=200
# 服务端使用的字符集默认为8比特编码的latin1字符集
character-set-server=utf8
# 创建新表时将使用的默认存储引擎
default-storage-engine=INNODB
#+END_SRC

注意：按照自己计算机的MySQL预安装路径合理的配置my.ini文件中的basedir和datadir参数；根据datadir参数的路径设置创建data目录，本机为MySQL安装目录下创建data目录。完成上述操作后，MySQL安装目录结构如下：

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64>dir
 驱动器 C 中的卷是 Local Disk
 卷的序列号是 ACAA-D769

 C:\MySQL\mysql-5.7.20-winx64 的目录

2017/11/06  22:33    <DIR>          .
2017/11/06  22:33    <DIR>          ..
2017/11/06  11:50    <DIR>          bin
2017/09/13  17:48            17,987 COPYING
2017/11/06  22:33    <DIR>          data
2017/11/06  11:50    <DIR>          docs
2017/09/13  20:27    <DIR>          include
2017/11/06  11:50    <DIR>          lib
2017/11/06  18:28               425 my.ini
2017/09/13  17:48             2,478 README
2017/11/06  11:50    <DIR>          share
               3 个文件         20,890 字节
               8 个目录 190,125,805,568 可用字节
#+END_SRC

定位到解压目录的bin目录下，执行初始化以下命令：

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64>cd bin

C:\MySQL\mysql-5.7.20-winx64\bin>mysqld.exe --initialize

C:\MySQL\mysql-5.7.20-winx64\bin>
#+END_SRC

注意：执行初始化命令前需要正确创建data目录并确保该目录为空。

执行MySQL服务安装命令：

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64\bin>mysqld.exe -install
Service successfully installed.
#+END_SRC

注意：安装成功则给出提示。

执行启动MySQL服务命令：

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64\bin>net start mysql
MySQL 服务正在启动 .
MySQL 服务已经启动成功。
#+END_SRC

也可以通过在开始菜单上点击右键选择 - 计算机管理 - 服务和应用程序 - 服务，找到MySQL服务，在此完成服务启动及其他配置操作。

以下是其他常用的MySQL命令行操作：

- 控制台 :: mysqld --console
- 关闭服务器 :: net stop mysql
- 卸载MySQL :: mysqld -remove

* 数据库系统基本配置

结束所有的MySQL进程，包括mysql.exe和mysqld.exe，可以在任务管理器中结束上述进程。

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64\bin>net stop mysql
MySQL 服务正在停止.
MySQL 服务已成功停止。
#+END_SRC

输入mysqld --skip-grant-tables，输入后，其他命令行已经无法再输入，需要另打开一个命令行窗口（2号）进行其他操作。

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64\bin>mysqld.exe --skip-grant-tables

#+END_SRC

在2号命令行窗口中定位到MySQL安装目录的bin目录下，执行mysql.exe，则无密码登录到MySQL数据库，并输出MySQL命令行操作符。

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64\bin>mysql.exe
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.20 MySQL Community Server (GPL)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
#+END_SRC

进行修改密码操作，MySQL命令行输入以下命令：

#+BEGIN_SRC 
mysql> update mysql.user set authentication_string=password('yourpassword') where user='root' and Host ='localhost';
Query OK, 1 row affected, 1 warning (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 1
#+END_SRC

其中，yourpassword位置即为所设置的MySQL的超级用户root的初始登录密码，请按需设置。

此时再在任务管理器结束所有的MySQL进程，包括mysql.exe和mysqld.exe，重新打开命令提示符（需要管理员权限）或使用Windows服务管理，启动MySQL服务器，即可用新密码登录。

MySQL服务启动成功后，在命令行提示符执行mysql.exe -u root -p即可以以刚才修改的root用户登录密码登录MySQL。

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64\bin>mysql.exe -u root -p
Enter password: ************
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.20

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
#+END_SRC

接下来，如果在MySQL命令提示符下执行诸如以下操作：

#+BEGIN_SRC dos
mysql> show databases;
ERROR 1820 (HY000): You must reset your password using ALTER USER statement before executing this statement.
mysql> exit
#+END_SRC

提示ERROR，必须重新为MySQL用户设置最终的密码，输入exit退出当前MySQL提示符状态。然后，在Windows命令行提示符执行：

#+BEGIN_SRC dos
C:\MySQL\mysql-5.7.20-winx64\bin>mysqladmin -u root -p password
Enter password: ************
New password: ****
Confirm new password: ****
Warning: Since password will be sent to server in plain text, use ssl connection to ensure password safety.
#+END_SRC

注意：原样输入以上mysqladmin -u root -p password命令，此处的password不是实际要设置的密码，而是关键字。

输入之前密码yourpassword，再输入两次新密码，则root用户密码设置成功。

之后，就可以使用新密码登录MySQL数据库了。

* 小结

MySQL数据库软件主要核心包含两个部分：

- mysqld.exe :: MySQL数据库服务器，以服务的形式注册到Windows系统，可以通过命令行工具net、Windows服务管理窗口管理该服务的启动和停止；如果你要访问数据库资源，必须保证mysqld服务正确启动。
- mysql.exe :: MySQL数据库客户端，属于命令行交互形式的MySQL客户端软件，与其他图形化客户端例如phpmyadmin等功能类似，必须连接本地或远程计算机的mysqld才能发挥作用。
