#+TITLE:     Tips
#+AUTHOR:    Xiaodong Wang
#+EMAIL:     wangxiaodong@ouc.edu.cn

#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  zh
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="orgcss/worg.css" />
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   ^:nil
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LATEX_HEADER: \usepackage{xeCJK}
#+LATEX_HEADER: \setCJKmainfont{SimSun}

* main方法为什么只能那么写？

main()方法的声明为public static void main(String args[])，且必须这么定义，这是Java的规范。

这么定义和JVM的运行有关系。当一个类中有main()方法，执行命令 *java 类名* 则会启动虚拟机执行该类中的main方法。由于JVM在运行这个Java应用程序的时候，首先会调用main方法，调用时不实例化这个类的对象而是通过类名直接调用，因此需要是限制为public static。对于java中的main方法，JVM限制不能有返回值，因此返回值类型为void。

* 抽象类有必要存在构造方法吗？

抽象类虽然自身不可以实例化，但是其子类覆盖了所有的抽象方法后是可以实例化的，所以抽象类的构造函数，适用于给其子类对象进行初始化。

* 对于构造函数，大家知道应该注意什么吗？

构造函数是对象的基本，没有构造函数就没有对象。如果在父类中（这里就是你的抽象类）中显示的定义了有参数的构造函数，在子类继承时就必须写一个构造函数来调用父类的构造函数。

如果父类中有没有参数的构造函数，在子类中可以不显示的调用父类的构造函数，Java会自动调用没有参数的构造函数。

如果编写一个Java Class时没有添加无参构造方法，那么编译器会自动添加无参构造方法。
但是如果编写时添加了有参构造方法而未添加无参构造方法，那么编译器只认有参构造方法而不会默认添加无参构造方法！所以，如果需要使用无参构造方法，一定要在类里面添加。

* 子类会继承父类的构造方法吗？

父类中的构造方法是不能继承的，但是在实例化子类的时候会调用父类的构造方法。

* 以下要删除所有元素c的代码有错么？运行完了还会有c没删除么？如有错请改错。

#+BEGIN_SRC java

import java.util.ArrayList;
import java.util.List;

public class Test {
	public static void main(String[] args) {
		List<String> li = new ArrayList<String>();

		li.add("a");
		li.add("b");
		li.add("c");
		li.add("d");
		li.add("c");
		li.add("c");
		li.add("e");
		li.add("c");

		for (int i = 0; i < li.size(); i++) {
			if (li.get(i).equals("c")) {
				li.remove(i);
			}
			
		}
		
		System.out.println(li);
	}
}
#+END_SRC

* TODO 关于文件的创建时间。

在Linux系统中没有文件创建时间的概念，只有文件的访问时间、修改时间、状态改变时间，即不能在文件的生命周期内永远知道文件的创建时间。与文件相关的几个时间包括：
- 访问时间 :: 读一次这个文件的内容，这个时间就会更新。比如对这个文件使用more命令。ls、stat命令都不会修改文件的访问时间。
- 修改时间 :: 对文件内容修改一次，这个时间就会更新。比如：vi后保存文件。ls -l列出的时间就是这个时间。
- 状态改变时间 :: 通过chmod命令更改一次文件属性，这个时间就会更新。

可以通过stat命令查看文件的详细的状态、准确的修改时间等。

- 如果文件创建后就没有修改过，那么修改时间 = 创建时间
- 如果文件创建后状态就没有改变过，那么状态改变时间 = 创建时间
- 如果文件创建后没有被读取过，那么访问时间 = 创建时间


